version: '3'

services:
  spark-master:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: spark_master
    ports:
      - "8080:8080" # gui - http//:localhost:8080
      - "7077:7077" # comm port
    volumes:
      - ./data:/opt/spark-data
      - ../spark_processing:/src
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    networks:
      - spark_network

  spark-worker-1:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: spark_worker_1
    depends_on:
      - spark-master
    volumes:
      - ./data:/opt/spark-data
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    networks:
      - spark_network

  spark-worker-2:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: spark_worker_2
    depends_on:
      - spark-master
    volumes:
      - ./data:/opt/spark-data
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    networks:
      - spark_network

networks:
  spark_network:
    driver: bridge
